### ISSUE TITLE
ENiGMA throws a database error on first launch

### ISSUE THREAD

**Issue by davestephens** [NuSkooler/enigma-bbs#90] opened 2016-08-29 10:54 UTC
**Short problem description**
The first time ENiGMA is run an error is thrown about missing database tables, and then exits. When relaunching, it goes away.

````
Error initializing: { [Error: SQLITE_ERROR: no such table: system_stat] errno: 1, code: 'SQLITE_ERROR' }
Error initializing: { [Error: SQLITE_ERROR: no such table: system_stat] errno: 1, code: 'SQLITE_ERROR' }
````

**Environment**
- Using Node 4.4, occurs on multiple 4.4.x versions
- `npm install` reports success
- Actual Node.js version (`node --version`): 4.4.7
- Operating system: Linux david-ThinkPad-T410 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux. Also occurs on Raspberry Pi Raspbian, so not suspected to be OS specific.
- Revision: b80cd18 (occured prior to this revision)

**Expected behavior**
Enigma should launch with no errors on first run.

**Actual behavior**
Enigma starts, then immediately exits with the following error:
````
Error initializing: { [Error: SQLITE_ERROR: no such table: system_stat] errno: 1, code: 'SQLITE_ERROR' }
Error initializing: { [Error: SQLITE_ERROR: no such table: system_stat] errno: 1, code: 'SQLITE_ERROR' }
````

**Steps to reproduce**
Perform a clean install of Enigma so no database exists, then launch Enigma for the first time.

**Comment by NuSkooler** [comment] 2016-08-29 20:16
Looks like I borked something -- I'll look into this tonight (hopefully) when looking at the new `install.sh` stuff.

**Comment by NuSkooler** [comment] 2016-08-29 23:42
I didn't get this after running the `install.sh` script for a new install. Can you provide a stack trace and log file?

**Comment by davestephens** [comment] 2016-09-01 12:34
Typically I can't reproduce this now, when I could consistently last week. I'm about to do a new install, will see if it happens again...

**Comment by NuSkooler** [comment] 2016-09-24 04:09
I was able to reproduce this a few times while adding some new DB/tables via `database.js`. Fixed by syncing table creation. Should now be good.

**Closed by NuSkooler** 2016-09-24 04:09 UTC
Labels: bug

**Comment by davestephens** [comment] 2016-09-24 11:30
Awesome, glad you finally saw the same thing :). I only saw it occasionally, and not since I reported it (!) - so assumed it was some annoying race condition.

**Comment by Fastidious** [comment] 2017-01-10 15:22
What was the fix for this? Getting same error from a fresh clone.

**Comment by NuSkooler** [comment] 2017-01-10 16:14
@Fastidious Yes this "should be fixed". Please post a stack + log if possible.
