### ISSUE TITLE
Message import stops

### ISSUE THREAD

**Issue by fransking** [NuSkooler/enigma-bbs#329] opened 2020-11-26 09:10 UTC
**Describe the Bug**
After a while (days to weeks) Enigma stops importing new FTN messages from the ftn_in folder.   A restart of Enigma will begin message import again and the folder will clear.  I'm running enigma inside an alpine docker image.  

**ftn_in directory listing**
pi@pi-kub0:/local/sbbs/mail/ftn_in $ ls -lh
total 3.1M
-rw-r--r-- 1 root root  727 Nov 26 05:33  0000ffc5.th0
-rw-r--r-- 1 root root  831 Nov 26 05:35  0000ffc5.th1
-rw-r--r-- 1 root root 1.2K Nov 26 06:25  0000ffc5.th2
-rw-r--r-- 1 root root 2.3K Nov 26 06:33  0000ffc5.th3
-rw-r--r-- 1 root root  856 Nov 26 06:52  0000ffc5.th4
-rw-r--r-- 1 root root  856 Nov 26 06:56  0000ffc5.th5
-rw-r--r-- 1 root root  856 Nov 26 07:13  0000ffc5.th6
-rw-r--r-- 1 root root 1.2K Nov 26 07:18  0000ffc5.th7
-rw-r--r-- 1 root root 1.6K Nov 26 07:28  0000ffc5.th8
-rw-r--r-- 1 root root  865 Nov 26 08:04  0000ffc5.th9
-rw-r--r-- 1 root root  863 Nov 26 08:08  0000ffc5.tha
-rw-r--r-- 1 root root  880 Nov 26 08:09  0000ffc5.thb
-rw-r--r-- 1 root root  857 Nov 26 08:35  0000ffc5.thc
-rw-r--r-- 1 root root  858 Nov 26 08:57  0000ffc5.thd
-rw-r--r-- 1 root root 1.4K Nov 26 01:33  0000ffc5.we7
-rw-r--r-- 1 root root 1.3K Nov 26 01:48  0000ffc5.we8
-rw-r--r-- 1 root root 1.4K Nov 26 02:20  0000ffc5.we9
-rw-r--r-- 1 root root  814 Nov 26 03:00  0000ffc5.wea
-rw-r--r-- 1 root root 1.4K Nov 26 03:01  0000ffc5.web
-rw-r--r-- 1 root root 1.1K Nov 26 03:18  0000ffc5.wec
-rw-r--r-- 1 root root 1.4K Nov 26 03:33  0000ffc5.wed
-rw-r--r-- 1 root root  933 Nov 26 04:16  0000ffc5.wee
-rw-r--r-- 1 root root  986 Nov 26 04:22  0000ffc5.wef
-rw-r--r-- 1 root root 1.2K Nov 26 04:30  0000ffc5.weg
-rw-r--r-- 1 root root 2.7K Nov 26 01:15  TBBSW32.tic
-rw-r--r-- 1 root root 3.0M Nov 26 01:12  TBBSW32.ZIP
-rw-r--r-- 1 root root    0 Nov 26 08:57 'toss!.now'

last log entry relating to message import (full log is attached)
[enigma-bbs.log](https://github.com/NuSkooler/enigma-bbs/files/5601669/enigma-bbs.log)

{"name":"ENiGMA½ BBS","hostname":"sbbs-enigma-9b59f6f79-vzd6m","pid":19,"level":20,"tic":"/mail/ftn_in/TBBSSRC.tic","file":"TBBSSRC.ZIP","msg":"Processing TIC file","time":"2020-11-26T01:25:48.900Z","v":0}
{"name":"ENiGMA½ BBS","hostname":"sbbs-enigma-9b59f6f79-vzd6m","pid":19,"level":30,"tic":"/mail/ftn_in/TBBSSRC.tic","file":"/mail/ftn_in/TBBSSRC.ZIP","area":"msgNetworks","msg":"TIC imported successfully","time":"2020-11-26T01:25:49.284Z","v":0}
{"name":"ENiGMA½ BBS","hostname":"sbbs-enigma-9b59f6f79-vzd6m","pid":19,"level":20,"tic":"/mail/ftn_in/TBBSW32.tic","file":"TBBSW32.ZIP","msg":"Processing TIC file","time":"2020-11-26T01:25:49.287Z","v":0}
pi@pi-kub0:/data/sbbs/logs $ cat enigma-bbs.log | grep ftn_in

Inside the running container I see what could be a stuck unzip process
bash-5.0# ps -A
PID   USER     TIME  COMMAND
    1 root     10:11 node /usr/local/bin/pm2-docker ./main.js
   19 root     28:01 node /enigma-bbs/main.js
  613 root      0:00 [unzip]
  614 root      0:00 /bin/bash
  624 root      0:00 ps -A

**Environment**
* [ Y] I am using Node.js v12.x LTS or higher
* [ Y] `npm install` or `yarn` reports success
* Actual Node.js version (`node --version`): v12.19.0
* Operating system (`uname -a` on *nix systems):  Linux sbbs-enigma-9b59f6f79-vzd6m 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l Linux
* Revision (`git rev-parse --short HEAD`):8aa878a
* Any additional relevant information about your setup: running on k3s (alpine based image https://github.com/fransking/docker-enigma-bbs/blob/master/Dockerfile)

**Comment by NuSkooler** [comment] 2020-11-26 19:00
@fransking I would expect the `unzip` binary to exit - are you sure your build of `unzip` is not waiting for (user) input of some sort? If you can, please capture the arguments to the hung PID. It should either be in the listing or extracting step of the archive processing. Given the arguments and archive (TBBSW32.ZIP), I'd guess we can reproduce the same behavior outside of enigma (but within your container).

If the above is true, some adjustments to the arguments for your `unzip` in `config.hjson` might do the trick.

**Comment by fransking** [comment] 2020-11-29 11:34
Good idea.  I shall try these out when it next happens and report back.

**Comment by fransking** [comment] 2020-12-21 09:24
I switched to 7za to rule out a specifc unzip issue but got the same behaviour today

    1 root     16:28 node /usr/local/bin/pm2-docker ./main.js
   19 root     43:09 node /enigma-bbs/main.js
  908 root      0:00 [7za]
  910 root      0:00 /bin/bash
  917 root      0:00 ps -A

I think I need to write a little wrapper to capture the output of what is going on here.  Will report back when I know more.

**Comment by NuSkooler** [comment] 2020-12-21 19:41
@fransking Sorry should have specified - hung PID of `unzip` or `7za` not Docker. You should be able to see this under a process tree or /proc from the Docker host.

**Comment by NuSkooler** [comment] 2021-01-29 02:09
@fransking  were you able to resolve this?

**Comment by fransking** [comment] 2021-02-01 18:08
hi - still seeing this issue yes both with zip and 7zip.   I need to find the time to write a wrapper script around the zip command so that I can log out to a file and see what is going on.

**Comment by fransking** [comment] 2021-02-07 09:55
Ok i have a trap script in place so hopefully I'll start to see some output

**Comment by fransking** [comment] 2021-02-08 09:33
Trap is working inside the container.  Just have to wait for the issue to occur now.  Might take a few days.

Sample output from a successful import.  First line is Enigma's command:

7za e -o/tmp/enigftnimport-201d90d866c64uD7LYw1Ug2HiJEW /mail/ftn_in/0000ffc5.mod

7-Zip (a) [32] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C.UTF-8,Utf16=on,HugeFiles=on,32 bits,4 CPUs LE)

Scanning the drive for archives:
1 file, 896 bytes (1 KiB)

Extracting archive: /mail/ftn_in/0000ffc5.mod
--
Path = /mail/ftn_in/0000ffc5.mod
Type = zip
Physical Size = 896

Everything is Ok

Size:       1255
Compressed: 896

**Comment by fransking** [comment] 2021-02-13 11:28
It stopped yesterday.  

ps -A inside the container shows the stuck trap.sh script

PID   USER     TIME  COMMAND
    1 root     13:33 node /usr/local/bin/pm2-docker ./main.js
   19 root     35:40 node /enigma-bbs/main.js
 1227 root      0:00 [trap.sh]

the output of the trap logs shows that this was the command

7za e -o/tmp/enigftnimport-191d9ab807f4RXelg4AugdUapAnl /mail/ftn_in/0000ffc5.fra

and attempting to run manually results in a prompt saying that the temp extract file already exists

Would you like to replace the existing file:
  Path:     /tmp/enigftnimport-191d9ab807f4RXelg4AugdUapAnl/0765a720.pkt
  Size:     4750 bytes (5 KiB)
  Modified: 2021-02-12 16:23:44
with the file from archive:
  Path:     0765a720.pkt
  Size:     4750 bytes (5 KiB)
  Modified: 2021-02-12 16:23:44
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? q

I don't know how enigma comes up with the temporary directory name but is it possible that it is trying to process the same file twice?

I do see that these tmp files are not always being cleaned up

bash-5.0# find /tmp/ -name "*.pkt" -print
/tmp/enigftnimport-191c7fc1ff3cm0u7hqqP5Yy2mhug/0c1dbaa8.pkt
/tmp/enigftnimport-191cc37f3a87RTUGWhPnnn28Pso2/00bedd16.pkt
/tmp/enigftnimport-201bdc6e25faefalHlpmgx9GDekj/09d69c1c.pkt
/tmp/enigftnimport-201bfb4f85f4yoBHbmxR9CLcgdDr/0db88047.pkt
/tmp/enigftnexport-191c3cc6cf002gNqJjWB57NgGY4O/02b08d81.pkt
/tmp/enigftnexport-191c3cc6cf002gNqJjWB57NgGY4O/3582e1b9.pkt
/tmp/enigftnimport-191d0bdc5937mLHadCR4iwqB7JlC/0939821d.pkt
/tmp/enigftnimport-191d5f866835CHP2JXmK40cW5qxZ/12e7b073.pkt
/tmp/enigftnimport-191d9ab807f4RXelg4AugdUapAnl/0765a720.pkt
/tmp/enigftnexport-191c189c21772iBpJjddZmLbcFu9/78e326a9.pkt
/tmp/enigftnexport-191c189c21772iBpJjddZmLbcFu9/60bc3e3b.pkt
/tmp/enigftnimport-191cd357bbb9zSg3WcQ5mk8dce3L/02127997.pkt
/tmp/enigftnexport-191c096ccdeaETHurJ2eaqomwLzZ/02d21f42.pkt
/tmp/enigftnexport-191c096ccdeaETHurJ2eaqomwLzZ/7cf32486.pkt
/tmp/enigftnexport-191bf4891429BEmnxA2I7R7ckLJn/1644fdfa.pkt
/tmp/enigftnexport-191bf4891429BEmnxA2I7R7ckLJn/69d4d67f.pkt
/tmp/enigftnimport-191d4352fa28HDHWBrc4pmGcSOMw/0f921298.pkt
/tmp/enigftnimport-191bc7aaa5f27Ccr9DWSi8PbLpna/082abef9.pkt
/tmp/enigftnimport-191d2e65702aA1c6CkGPhOl8pPmM/0d4bbbb8.pkt
/tmp/enigftnimport-191c189c218a51XrFFcuwkC3Rs1K/112c8341.pkt
/tmp/enigftnimport-191bea69dfddmfKckyx49H8zMu5J/0b084e07.pkt
/tmp/enigftnimport-191c28ea3ddao3xMplyOha6mbInk/019c45f6.pkt
/tmp/enigftnexport-191c4c70e05e16NjY4lkY8Pumasu/1cc0e5d6.pkt

**Comment by fransking** [comment] 2021-02-13 11:40
Actually i think the above is the last logs of a successful import because in the engima logs I see that it did import this message.

{"name":"ENiGMA½ BBS","hostname":"sbbs-enigma-54c886b4bd-llkxm","pid":19,"level":30,"areaSuccess":{"fsx_dat":1},"areaFail":{},"otherFail":0,"packetPath":"/tmp/enigftnimport-191d9ab807f4RXelg4AugdUapAnl/065b1a1a.pkt","msg":"Import complete","time":"2021-02-10T23:25:57.438Z","v":0}

Whether the process then just didn't terminate or whether the subsequent spawn failed I'm not sure of at the moment

**Comment by NuSkooler** [comment] 2021-02-13 18:08
@fransking Awesome, this I can work with. 

First thing: The leftover files are likely due to #322 which happens when using containers. This should be fixed as of 5 days ago. You'll need to pull and update your node modules (`yarn` or `npm install`). Since you're using containers, this means you'll need to update your container itself depending how you have things set up.

Second thing: I think we'll want to add `-y` to the `7za` extraction args. Assume yes to all queries "just in case". We don't want hanging PIDs either way and I don't see that p7zip (the Linux port) having explicit "overwrite existing" options.

I just pushed a change to the default 7za extract options. If you're using a custom configuration you'll need to update that.

**Comment by fransking** [comment] 2021-02-13 18:17
Thanks a lot for looking into this.  I've re-built my images to the latest source using arm32v7/node:14-alpine as a base, added the -y arg to my config and left the trap in place.   Now we wait :)

**Comment by fransking** [comment] 2021-02-22 08:51
It's happened again I'm afraid - defunct trap process:

 1211 root      0:00 [trap.sh]

last successfully executed command (with -y flag)
7za e -y -o/tmp/enigftnimport-191dceb0063eugMqGXsIkddjYYjh /mail/ftn_in/0000ffc5.sua

A few folders still in /tmp

bash-5.0# ls /tmp
enigftnexport-191dceb00621fSUX4dUEtgOhptnS
enigftnexport-201db163ebb0wCSb9OZ3PMRDorkd
enigftnexport-201dbf78c866d6xDbTRlloe8h031
enigftnimport-191dceb0063eugMqGXsIkddjYYjh
enigftnimport-201db163ebbeCwTkyKnryH0uyUAP
enigftnimport-201dbf78c87cWcB2oMcM6A1Q660x
bash-5.0#

**Comment by NuSkooler** [comment] 2021-02-22 22:18
@fransking And you're sure you have the new module from #322? This has never been seen in anything but containers which #322 describes

Further, do you know what 7za is waiting on ? -y assumes yes to all queries so will overwrite files.

**Comment by fransking** [comment] 2021-02-24 10:06
Yes definitely got this version bash-5.0# cat package.json

  "types": "./typings/node-pty.d.ts",
  "version": "0.10.0"
}

I'm not convinced that it is zip or 7za hanging around waiting for user input because if that was the case I should see the process still running.  Instead what I see is the defunct trap.sh script only

PID USER TIME COMMAND
1 root 13:33 node /usr/local/bin/pm2-docker ./main.js
19 root 35:40 node /enigma-bbs/main.js
1227 root 0:00 [trap.sh]


This script is just the following:

#!/bin/bash
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>/var/tmp/log.out 2>&1
echo $@


It's like node-pty isn't terminating or allowing the process to terminate normally or that it simply is failing to start the process properly.    I am using an Alpine linux based container and so using musl instead of glibc.  I can try a vanilla debian container instead to rule some musl incompatibility.

**Comment by NuSkooler** [comment] 2021-02-24 17:01
There is now a container built via the GitHub CI. You might try that.

**Comment by fransking** [comment] 2021-02-24 17:31
Thanks I'll have a look.  Might need to roll my own for armhf though but it's not a big issue.

**Comment by NuSkooler** [comment] 2022-02-02 04:43
Can this be closed?

**Comment by fransking** [comment] 2022-02-02 05:18
Hi.  I never got to the bottom of it unfortunately. It only happens on arm and the same docker container built for x64 never exhibits this problem so I was left wondering if it was some strange issue with the underlying node-pty library.  

I would close it if no one else is reporting it as an issue as I'm on x64 now.

**Comment by NuSkooler** [comment] 2022-02-02 05:50
@fransking Thanks, I'll close it for now then.

**Closed by NuSkooler** 2022-02-02 05:50 UTC
Labels: bug
