### ISSUE TITLE
Fuzzy characters upon entering DoorParty

### ISSUE THREAD

**Issue by XBessa** [NuSkooler/enigma-bbs#98] opened 2016-09-23 00:56 UTC
For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

**Short problem description**
I have configured my system to use DoorParty. When i connect to DoorParty, the graphical ANSI characters are all garbled. 

[
![unnamed](https://cloud.githubusercontent.com/assets/22383201/18770700/1b0cd076-810f-11e6-93a3-3d586816e3e5.jpg)
](url)

**Environment**
- [X] I am using Node.js v4.x or higher
- [X] `npm install` reports success
- Actual Node.js version (`node --version`): 4.4.0
- Operating system (`uname -a` on *nix systems): Linux ip-172-31-26-239 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Revision (`git rev-parse --short HEAD`):

**Expected behavior**
DoorParty should present graphical characters
**Actual behavior**
DoorParty presents garbled characters
**Steps to reproduce**
Configure your system to enter DoorParty
Enter DoorParty

**Comment by NuSkooler** [comment] 2016-09-23 02:14
@XBessa Thanks for the report. Have you tried other terminals?

Also, this looks suspiciously like something that was semi-recently fixed by swapping out `ptyw.js` with a custom version with some fixes. Can you try the following and report back?

```
cd /path/to/your/engima-bbs/
npm remove ptyw.js
npm install
```

Restart ENiGMA½ and try again.

**Comment by NuSkooler** [comment] 2016-09-30 05:17
@XBessa Did the above fix the issue for you?

**Comment by XBessa** [comment] 2016-10-01 18:09
Nope, still fuzzy screen when I log into door party...

2016-09-30 2:17 GMT-03:00 Bryan Ashby <notifications@github.com>:

**Comment by NuSkooler** [comment] 2016-10-01 18:33
@XBessa Did you try the steps above? What is the contents of your `package.json` file in the `enigma-bbs` dir? Another thing you can try: Connect to `xibalba.l33t.codes:44510` and see if DoorParty is corrupt there.

**Comment by XBessa** [comment] 2016-10-01 18:36
I did, but here it goes:

ubuntu@ip-172-31-26-239:~/enigma-bbs$ cat package.json
{
  "name": "enigma-bbs",
  "version": "0.0.1-alpha",
  "description": "ENiGMA½ Bulletin Board System",
  "author": "Bryan Ashby <bryan@l33t.codes>",
  "license": "BSD-2-Clause",
  "repository": {
    "type": "git",
    "url": "https://github.com/NuSkooler/enigma-bbs.git"
  },
  "homepage": "https://github.com/NuSkooler/enigma-bbs",
  "bugs": {
    "url": "https://github.com/NuSkooler/enigma-bbs/issues"
  },
  "keywords": [
    "bbs",
    "telnet"
  ],
  "dependencies": {
    "async": "^1.5.1",
    "binary": "0.3.x",
    "buffers": "0.1.x",
    "bunyan": "^1.7.1",
    "farmhash": "^1.2.1",
    "fs-extra": "0.26.x",
    "gaze": "^0.5.2",
    "hjson": "1.7.x",
    "iconv-lite": "^0.4.13",
    "inquirer": "^1.1.0",
    "later": "1.2.0",
    "lodash": "^3.10.1",
    "minimist": "1.2.x",
    "moment": "^2.11.0",
    "node-uuid": "^1.4.7",
    "ptyw.js": "NuSkooler/ptyw.js",
    "sqlite3": "^3.1.1",
    "ssh2": "^0.5.1",
    "temp": "^0.8.3"
  },
  "engines": {
    "node": ">=4.2.0"
  }
}

I will connect to Xibalba and see how it goes.

2016-10-01 15:33 GMT-03:00 Bryan Ashby <notifications@github.com>:

**Comment by XBessa** [comment] 2016-10-01 18:40
It gets garbled the same way when I connect to DoorParty through Xibalba :)

2016-10-01 15:36 GMT-03:00 Flavio Bessa <fcbessa@gmail.com>:

**Comment by NuSkooler** [comment] 2016-10-01 18:57
@XBessa Thanks for your quick reply. It works for me in NetRunner and SyncTERM on Xibalba. For now, I suggest using one of those. What terminal are you using? I'll try to duplicate with that -- assuming I get the same issue (I imagine I will) I'll change the title of this bug to fix support for said terminal.

**Comment by XBessa** [comment] 2016-10-01 19:05
I am using ZOC... And I start to believe that this might be the case,
because with ZOC I have to use Linux as a terminal in order to get proper
ANSI coding... i will test with Syncterm and let you know.

Em sábado, 1 de outubro de 2016, Bryan Ashby <notifications@github.com>
escreveu:

**Comment by NuSkooler** [comment] 2016-10-01 19:07
@XBessa Do you have ZOC set to ANSI-BBS? I haven't tried, but their page says it supports it. I'll be downloading and looking into it further soon.

**Comment by XBessa** [comment] 2016-10-01 19:09
If I use ANSI-BBS, all Ansi at ENIGMA will appear garbled... only way to
see it correctly is changing to Linux...

Em sábado, 1 de outubro de 2016, Bryan Ashby <notifications@github.com>
escreveu:

**Comment by NuSkooler** [comment] 2016-10-01 19:17
@XBessa I just downloaded ZOC for Windows & can reproduce this. ZOC is announcing itself as `pcansi`, which ENiGMA½ doesn't currently understand as ANSI-BBS. I'll be pushing a fix for this soon.

**Comment by NuSkooler** [comment] 2016-10-01 19:31
Added `pcansi` = ANSI-BBS/CP437 support @ f8c49906462d3776ffc3d2c879cf13127068595c

**Closed by NuSkooler** 2016-10-01 19:31 UTC

**Comment by XBessa** [comment] 2016-10-01 19:47
Cool! Thanks!

Em sábado, 1 de outubro de 2016, Bryan Ashby <notifications@github.com>
escreveu:
