### ISSUE TITLE
Drawing issues if terminal lacks full ANSI-BBS support

### ISSUE THREAD

**Issue by Fastidious** [NuSkooler/enigma-bbs#24] opened 2015-11-20 19:10 UTC
Using OS X default terminal:

![untitled](https://cloud.githubusercontent.com/assets/8352292/11309211/83dc0854-8f90-11e5-839f-626d510f6cc8.gif)

**Comment by NuSkooler** [comment] 2015-11-20 20:09
Looks as if we just need to ensure the SGR style is properly (re)set when focus is placed.

**Comment by NuSkooler** [comment] 2015-11-21 21:12
Update: I can reproduce this on my OS X box using the default terminal. Not sure what the issue is exactly yet. I also noticed that the edit position display ends up with the last "missing" character being typed in.

For now, I suggest using a more ANSI-BBS terminal such as EtherTerm, SyncTERM, NetRunner, etc.

**Comment by Fastidious** [comment] 2015-11-21 21:22
I understand that is might work better under the clients you listed, but if you are looking for greater usage, with minimum effort, it would be nice to make it work on what is available out of the box. I can declare `ansi` on Terminal.app, and still the same.

**Comment by NuSkooler** [comment] 2015-11-21 23:52
I'm not closing this -- it is a a but, it's just lower priority than others since AFAIK it's only reproducible in the default OS X terminal. iTerm, Linux terminals, and all the popular BBS terminals I know of work fine.

**Comment by NuSkooler** [comment] 2015-11-23 04:00
The problem appears to be that OS X's `Terminal.app` does not adhere to ANSI-BBS. Specifically in this case, Save Cursor Position (`ESC[s`) and Restore Cursor Position (`ESC[u`). This terminal does have DEC "private" sequences for these -- Save Cursor: `ESC7` and Restore Cursor `ESC8`.

As of now, this terminal will not be supported.

In the future, it may be useful to introduce a termcap mapping of sorts. Terminal.app does give some hints about itself via the TERM and DISPLAY variables. We may be able to detect this and use the alternate sequences.

**Comment by NuSkooler** [comment] 2018-12-10 20:49
#222 should fix this.

**Comment by NuSkooler** [comment] 2022-04-08 06:08
I believe this to be fixed now, but I'll try to get some time to try it myself as well. Can anyone confirm?

**Comment by NuSkooler** [comment] 2023-08-31 03:27
Closing. This should be working now with changes removing SCP/RCP dependencies.

**Closed by NuSkooler** 2023-08-31 03:27 UTC
Labels: enhancement
