### ISSUE TITLE
Making it work with xterm

### ISSUE THREAD

**Issue by Fastidious** [NuSkooler/enigma-bbs#85] opened 2016-08-21 17:21 UTC
Right now it doesn't work (well, connects, but result is quasi-gibberish) with xterm. Can it be made, so it is more widely usable? Requiring a client to connect drastically reduces enigmaBBS acceptance and usage.

**Comment by NuSkooler** [comment] 2016-08-21 21:09
@Fastidious This is a dupe of a issue #24 you already logged. OS X's `Terminal.app` doesn't support ANSI-BBS, and therefor is currently not supported.

A fix for this would require detection of `Terminal.app` or standard ESC vs DEC private (which that terminal is using) and the `ansi_term.js` module to have knowledge of the underlying term (e.g. to send special ESC's vs standard).

Please log any follow up/etc. to #24. As this is likely a issue with nearly any BBS soft, it's not a huge priority as of now. Use a ANSI-BBS compatible terminal. 

Note that PR's are welcome :)

**Closed by NuSkooler** 2016-08-21 21:09 UTC

**Comment by Fastidious** [comment] 2016-08-21 21:44
Apologies, I completely forgot I logged this one already.
